/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#4edea3',
        'primary-container': '#10b981',
        'primary-fixed': '#6ffbbe',
        'primary-fixed-dim': '#4edea3',
        'on-primary': '#003824',
        'on-primary-container': '#00422b',
        'on-primary-fixed': '#002113',
        'on-primary-fixed-variant': '#005236',
        'inverse-primary': '#006c49',
        'secondary': '#d0bcff',
        'secondary-container': '#571bc1',
        'secondary-fixed': '#e9ddff',
        'secondary-fixed-dim': '#d0bcff',
        'on-secondary': '#3c0091',
        'on-secondary-container': '#c4abff',
        'on-secondary-fixed': '#23005c',
        'on-secondary-fixed-variant': '#5516be',
        'tertiary': '#ffb3af',
        'tertiary-container': '#fc7c78',
        'tertiary-fixed': '#ffdad7',
        'tertiary-fixed-dim': '#ffb3af',
        'on-tertiary': '#650911',
        'on-tertiary-container': '#711419',
        'on-tertiary-fixed': '#410005',
        'on-tertiary-fixed-variant': '#842225',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'background': '#0e1511',
        'on-background': '#dde4dd',
        'surface': '#0e1511',
        'surface-dim': '#0e1511',
        'surface-bright': '#343b36',
        'surface-variant': '#2f3632',
        'surface-tint': '#4edea3',
        'surface-container': '#1a211d',
        'surface-container-low': '#161d19',
        'surface-container-high': '#242c27',
        'surface-container-highest': '#2f3632',
        'surface-container-lowest': '#09100c',
        'on-surface': '#dde4dd',
        'on-surface-variant': '#bbcabf',
        'inverse-surface': '#dde4dd',
        'inverse-on-surface': '#2b322d',
        'outline': '#86948a',
        'outline-variant': '#3c4a42',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'bento-gap': '20px',
        xs: '8px',
        sm: '16px',
        md: '24px',
        lg: '32px',
        xl: '48px',
        'base': '4px',
        'container-max': '1440px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'code-md': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '1.5', fontWeight: '400' }],
        'code-md': ['14px', { lineHeight: '1.4', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '-1000px 0' },
          '100%': { backgroundPosition: '1000px 0' },
        },
        drawLine: {
          to: { strokeDashoffset: '0' },
        },
        entrance: {
          from: { opacity: '0', transform: 'translateY(16px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        slideIn: {
          from: { transform: 'translateX(100%)' },
          to: { transform: 'translateX(0)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        pulse2: {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.15' },
          '50%': { transform: 'scale(1.1)', opacity: '0.1' },
        },
      },
      animation: {
        shimmer: 'shimmer 2s infinite linear',
        entrance: 'entrance 400ms cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'slide-in': 'slideIn 300ms cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'fade-in': 'fadeIn 200ms ease forwards',
        'pulse2': 'pulse2 4s ease-in-out infinite alternate',
      },
      boxShadow: {
        'emerald-sm': '0 0 8px rgba(78,222,163,0.3)',
        'emerald-md': '0 0 20px rgba(16,185,129,0.2)',
        'emerald-lg': '0 0 30px rgba(16,185,129,0.3)',
      },
    },
  },
  plugins: [],
};
