import { useNavigate } from 'react-router-dom';
import { useState } from 'react';
import { motion } from 'framer-motion';
import {
  AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
} from 'recharts';

// ── Data sets for different time ranges ─────────────────────────────────────
const dataByRange: Record<string, { date: string; calls: number }[]> = {
  '7d': [
    { date: 'May 24', calls: 32000 },
    { date: 'May 25', calls: 28000 },
    { date: 'May 26', calls: 35000 },
    { date: 'May 27', calls: 41000 },
    { date: 'May 28', calls: 38000 },
    { date: 'May 29', calls: 44000 },
    { date: 'May 30', calls: 38000 },
  ],
  '30d': [
    { date: 'May 1', calls: 12000 },
    { date: 'May 5', calls: 18500 },
    { date: 'May 10', calls: 14000 },
    { date: 'May 15', calls: 24000 },
    { date: 'May 20', calls: 31000 },
    { date: 'May 25', calls: 28000 },
    { date: 'May 30', calls: 38000 },
  ],
  '90d': [
    { date: 'Mar', calls: 95000 },
    { date: 'Apr', calls: 120000 },
    { date: 'May 1', calls: 100000 },
    { date: 'May 15', calls: 145000 },
    { date: 'May 30', calls: 162000 },
  ],
};

const stats = [
  { label: 'Total Keys', value: '142', icon: 'vpn_key', sparkline: true, route: '/keys' },
  { label: 'Active Keys', value: '118', icon: 'check_circle', badge: '+12%', badgeColor: 'text-primary bg-primary/10', route: '/keys' },
  { label: 'Expired/Revoked', value: '24', icon: 'cancel', badge: '-2', badgeColor: 'text-error bg-error/10', iconColor: 'text-error', route: '/alerts' },
  { label: 'Total API Calls', value: '8.4M', icon: 'data_usage', sparkline: true, route: '/analytics' },
];

const activityLog = [
  { key: 'analytics_read_v2', action: 'generated by system', time: '10 minutes ago', color: '#10b981' },
  { key: 'legacy_crm_sync', action: 'rotated manually', time: '2 hours ago', color: '#d0bcff' },
  { key: 'temp_debug_tk', action: 'expired naturally', time: 'Yesterday, 14:32', color: '#ffb4ab' },
];

const expiryAlerts = [
  { name: 'prod_eu_gateway', days: '2 days', urgency: 'text-error' },
  { name: 'dev_stripe_hooks', days: '5 days', urgency: 'text-tertiary' },
];

const container = { hidden: {}, show: { transition: { staggerChildren: 0.07 } } };
const item = { hidden: { opacity: 0, y: 16 }, show: { opacity: 1, y: 0, transition: { duration: 0.3 } } };

export default function Dashboard() {
  const navigate = useNavigate();
  const [activeRange, setActiveRange] = useState<'7d' | '30d' | '90d'>('30d');
  const [rotatedKeys, setRotatedKeys] = useState<Set<string>>(new Set());

  const handleRotate = (name: string) => {
    setRotatedKeys(prev => new Set([...prev, name]));
    setTimeout(() => {
      setRotatedKeys(prev => { const n = new Set(prev); n.delete(name); return n; });
    }, 2000);
  };

  const quickActions = [
    { icon: 'key', label: 'New Key', color: 'text-primary', action: () => navigate('/keys') },
    { icon: 'download', label: 'Export CSV', color: 'text-on-surface-variant', action: () => { const a = document.createElement('a'); a.href = 'data:text/csv;charset=utf-8,Key,Calls\nPROD_AUTH,1248392\nMOBILE_IOS,892104'; a.download = 'keyforge-export.csv'; a.click(); } },
    { icon: 'person_add', label: 'Invite User', color: 'text-on-surface-variant', action: () => navigate('/team') },
    { icon: 'leaderboard', label: 'Analytics', color: 'text-on-surface-variant', action: () => navigate('/analytics') },
  ];

  return (
    <div className="max-w-[1440px] mx-auto flex flex-col gap-bento-gap">
      <header className="mb-2">
        <h2 className="font-bold text-on-surface" style={{ fontSize: 32, lineHeight: 1.2 }}>Overview</h2>
        <p className="text-on-surface-variant mt-1 text-sm">Monitor your API ecosystem health.</p>
      </header>

      <motion.div variants={container} initial="hidden" animate="show" className="grid grid-cols-1 md:grid-cols-3 gap-bento-gap">
        {/* ── Stats Row ─────────────────────────────────────── */}
        <motion.div variants={item} className="col-span-1 md:col-span-3 grid grid-cols-2 lg:grid-cols-4 gap-bento-gap">
          {stats.map((s) => (
            <button
              key={s.label}
              onClick={() => navigate(s.route)}
              className="bento-card p-6 flex flex-col justify-between min-h-[120px] text-left w-full group"
            >
              <div className="flex justify-between items-start mb-4">
                <span className="text-on-surface-variant text-sm group-hover:text-primary transition-colors">{s.label}</span>
                <span
                  className={`material-symbols-outlined ${s.iconColor ?? 'text-outline'} group-hover:scale-110 transition-transform`}
                  style={{ fontSize: 22 }}
                >
                  {s.icon}
                </span>
              </div>
              <div className="flex items-end justify-between">
                <span className="font-black text-on-surface" style={{ fontSize: 36, lineHeight: 1 }}>{s.value}</span>
                {s.badge && (
                  <span className={`font-mono text-xs px-2 py-1 rounded ${s.badgeColor}`}>{s.badge}</span>
                )}
                {s.sparkline && (
                  <svg className="w-16 h-8" viewBox="0 0 100 30" fill="none" strokeWidth={2}>
                    <path d="M0,20 Q10,25 20,15 T40,10 T60,25 T80,5 T100,10" stroke="#4edea3" className="sparkline-path" />
                  </svg>
                )}
              </div>
            </button>
          ))}
        </motion.div>

        {/* ── API Usage Chart ────────────────────────────────── */}
        <motion.div variants={item} className="col-span-1 md:col-span-2 bento-card p-6 flex flex-col min-h-[360px]">
          <div className="flex justify-between items-center mb-6">
            <h3 className="font-semibold text-on-surface" style={{ fontSize: 20 }}>API Usage Volume</h3>
            <div className="flex bg-surface-container-high rounded p-1 gap-1">
              {(['7d', '30d', '90d'] as const).map((t) => (
                <button
                  key={t}
                  onClick={() => setActiveRange(t)}
                  className={`px-3 py-1 rounded font-mono text-xs transition-all ${
                    activeRange === t
                      ? 'bg-primary/20 text-primary shadow'
                      : 'text-on-surface-variant hover:text-on-surface'
                  }`}
                >
                  {t}
                </button>
              ))}
            </div>
          </div>
          <div className="flex-1">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={dataByRange[activeRange]} margin={{ top: 4, right: 8, left: -20, bottom: 0 }}>
                <defs>
                  <linearGradient id="emeraldGrad" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#10b981" stopOpacity={0.3} />
                    <stop offset="95%" stopColor="#10b981" stopOpacity={0} />
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(60,74,66,0.3)" />
                <XAxis dataKey="date" stroke="#86948a" tick={{ fontSize: 11, fontFamily: 'JetBrains Mono' }} />
                <YAxis stroke="#86948a" tick={{ fontSize: 11, fontFamily: 'JetBrains Mono' }} />
                <Tooltip
                  contentStyle={{ background: '#1a211d', border: '1px solid rgba(60,74,66,0.5)', borderRadius: 8, color: '#dde4dd' }}
                  labelStyle={{ color: '#bbcabf', fontFamily: 'JetBrains Mono', fontSize: 11 }}
                />
                <Area type="monotone" dataKey="calls" stroke="#4edea3" strokeWidth={2.5} fill="url(#emeraldGrad)" />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </motion.div>

        {/* ── Expiry Alerts ─────────────────────────────────── */}
        <motion.div variants={item} className="col-span-1 bento-card p-6 flex flex-col">
          <h3 className="font-semibold text-on-surface mb-1 flex items-center gap-2" style={{ fontSize: 20 }}>
            <span className="material-symbols-outlined text-error" style={{ fontSize: 22 }}>warning</span>
            Action Required
          </h3>
          <p className="font-mono text-xs text-on-surface-variant mb-4 tracking-wider">Keys expiring in &lt; 7 days</p>
          <div className="flex flex-col gap-3 overflow-y-auto custom-scrollbar pr-1">
            {expiryAlerts.map((a) => {
              const done = rotatedKeys.has(a.name);
              return (
                <div key={a.name} className="bg-surface-container rounded-lg p-3 border border-outline-variant/50">
                  <div className="flex justify-between items-start mb-2">
                    <span className="font-mono text-sm text-on-surface truncate">{a.name}</span>
                    <span className={`font-mono text-xs ${a.urgency}`}>{a.days}</span>
                  </div>
                  <motion.button
                    whileTap={{ scale: 0.97 }}
                    onClick={() => handleRotate(a.name)}
                    disabled={done}
                    className={`w-full font-mono text-xs py-1.5 rounded border transition-colors ${
                      done
                        ? 'bg-primary/20 text-primary border-primary/30'
                        : 'bg-surface-variant hover:bg-surface-bright text-on-surface border-outline-variant'
                    }`}
                  >
                    {done ? '✓ Rotated' : 'Rotate Now'}
                  </motion.button>
                </div>
              );
            })}
            <button
              onClick={() => navigate('/alerts')}
              className="text-xs text-primary hover:underline text-center mt-1 font-mono"
            >
              View all alerts →
            </button>
          </div>
        </motion.div>

        {/* ── Recent Activity ─────────────────────────────────── */}
        <motion.div variants={item} className="col-span-1 md:col-span-2 bento-card p-6">
          <div className="flex justify-between items-center mb-6">
            <h3 className="font-semibold text-on-surface" style={{ fontSize: 20 }}>Recent Activity Log</h3>
            <button
              onClick={() => navigate('/keys')}
              className="text-xs text-primary hover:underline font-mono"
            >
              View all keys →
            </button>
          </div>
          <div className="relative pl-6 border-l border-outline-variant/30 flex flex-col gap-6">
            {activityLog.map((a, i) => (
              <div key={i} className="relative">
                <div className="absolute -left-[31px] bg-surface rounded-full p-1 border" style={{ borderColor: a.color }}>
                  <div className="w-2 h-2 rounded-full" style={{ backgroundColor: a.color }} />
                </div>
                <p className="text-on-surface text-sm">
                  Key{' '}
                  <span className="font-mono text-sm" style={{ color: a.color }}>{a.key}</span>{' '}
                  {a.action}.
                </p>
                <p className="font-mono text-xs text-on-surface-variant mt-1 tracking-wider">{a.time}</p>
              </div>
            ))}
          </div>
        </motion.div>

        {/* ── Quick Actions ─────────────────────────────────── */}
        <motion.div variants={item} className="col-span-1 bento-card p-6 flex flex-col">
          <h3 className="font-semibold text-on-surface mb-6" style={{ fontSize: 20 }}>Quick Actions</h3>
          <div className="grid grid-cols-2 gap-3 flex-1">
            {quickActions.map((qa) => (
              <motion.button
                key={qa.label}
                whileHover={{ y: -2 }}
                whileTap={{ scale: 0.97 }}
                onClick={qa.action}
                className="bg-surface-container hover:bg-surface-bright border border-outline-variant/30 rounded-lg p-4 flex flex-col items-center justify-center gap-2 transition-all group"
              >
                <span className={`material-symbols-outlined ${qa.color} group-hover:text-primary transition-colors`} style={{ fontSize: 24 }}>{qa.icon}</span>
                <span className="font-mono text-xs text-on-surface tracking-wider">{qa.label}</span>
              </motion.button>
            ))}
          </div>
        </motion.div>
      </motion.div>
    </div>
  );
}
